version: '3.8'
services:
  api:
    build: 
        dockerfile: Api/Dockerfile
        context: .
    ports:
      - "5000:8080"
    depends_on:
      - db
    volumes:
      - ./uefa.db:/app/Data/uefa.db

  ui:
    build:
        dockerfile: UI/Dockerfile
        context: .
    ports:
      - "3000:80"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
