@host = http://localhost:5228

GET {{host}}/
Accept: application/json
###

GET {{host}}/api/countries
Accept: application/json
###

GET {{host}}/api/countries/id
Accept: application/json
###

GET {{host}}/api/teams
Accept: application/json
###

GET {{host}}/api/teams/id
Accept: application/json
###